### ISSUE TITLE
BEDTOOLS_INTERSECT_FILTER is not invoked before accessing the output attribute in release version

### ISSUE THREAD

**Issue by jianhong** [nf-core/nascent#105]
### Description of the bug

BEDTOOLS_INTERSECT_FILTER is not invoked before accessing the output attribute in script subworkflows/local/transcript_identification.nf at line 66 when params.filter_bed is not defined or set to false.

Fix:

remove codes from line 64 to 68 in file transcript_identification.nf

**Comment by Emiller88** [comment]
Hello! Thanks for reporting. I have a hunch this was fixed in https://github.com/nf-core/nascent/pull/94, but I don't have enough information about what command you ran.

**Comment by jianhong** [comment]
@Emiller88 I see you fixed it in dev version. What I tried is release version. Anyway, good to see it already fixed.

**Comment by Emiller88** [comment]
Awesome, feel free to reopen if it doesn't work with `-r dev`! 

Just been hung up in review limbo for a bit.
