### ISSUE TITLE
Which assay type (GRO-seq, PRO-seq ... etc) should I use for EU-seq?

### ISSUE THREAD

**Issue by YoshikiHigashijima** [nf-core/nascent#118]
### Description of feature

My question is which assay type (GRO-seq, PRO-seq .. etc.,) should I use for EU-seq analysis? This is the outline of EU-seq (PMID: 34485932). Briefly, nascent RNA is labeled by 5-EU in vivo. Afterword, EU-labeled RNAs are enriched, and reverse transcribed and amplified cDNAs having barcodes are sequenced. It looks like GRO-seq or PRO-seq but a bit different because in EU-seq experiment nascent RNAs are labeled _in vivo_ without nuclear isolation and cell lysis steps.

**Comment by edmundmiller** [comment]
Think we fixed this in Slack, feel free to re-open! https://nfcore.slack.com/archives/CFXHZD9TR/p1694596296008679

>Edmund
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694616108779009?thread_ts=1694596296.008679&cid=CFXHZD9TR)
That's a good question, it definitely doesn't have out of the box PINTS support, but we can tweak the params. Looks like it should be similar to GRO-seq or PRO-seq?
I'll get back to you on it when I have some more time, could you make a GitHub issue for it? https://github.com/nf-core/nascent/issues/new?template=feature_request.yml
Edmund
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694616208634959?thread_ts=1694596296.008679&cid=CFXHZD9TR)
If you could find a repo with an example of processing it, that would be a huge help or a publication on how the processing is done(Might be in the one you sent, just link in the issue for the section of it please!)
東島佳毅
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694653813125689?thread_ts=1694596296.008679&cid=CFXHZD9TR)
Thank you for your response. Below is the processing method that my previous colleague used. This work is published this year (PMID: 37024579). I want to analyze EU-seq data by myself with nf-core!
東島佳毅
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694653830415219?thread_ts=1694596296.008679&cid=CFXHZD9TR)
EU RNA-seq differential gene expression analysis
Previously published ([GSE146328](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE146328))[21](https://www.nature.com/articles/s41588-023-01348-4#ref-CR21) EU RNA-seq data of ESCs treated with DMSO or A-485 (10 µM, 30, 60 and 120 min) were reprocessed. Trimming of adapters and low-quality sequences (Phred quality score < 20) was performed using Cutadapt v.4.2 (https://doi.org/10.14806/ej.17.1.200). Read sequences were aligned to mm10 (mouse) using the Burrows–Wheeler Aligner (BWA) with default parameters (BWA v.0.7.10)[59](https://www.nature.com/articles/s41588-023-01348-4#ref-CR59). Multi-mapped reads and reads with more than three mismatches were removed using SAMtools (v.1.4)[60](https://www.nature.com/articles/s41588-023-01348-4#ref-CR60). Reads mapped to the ribosomal and transfer RNA region obtained from the UCSC genome browser were removed using BEDTools (v.2.23)[61](https://www.nature.com/articles/s41588-023-01348-4#ref-CR61). For 30, 60 and 120 min time point data, based on the polymerase II elongation rates, maximum 30, 90 and 240 kb gene body regions from the TSS were used for differential gene expression analysis. The number of reads mapped to the defined regions was counted using HTSeq (v.0.11.1)[62](https://www.nature.com/articles/s41588-023-01348-4#ref-CR62). log2 fold change and P values were calculated at individual time points using DEseq2 (v.1.32.0)[63](https://www.nature.com/articles/s41588-023-01348-4#ref-CR63) with the default scaling method (median of relative abundance). Expressed genes were determined as described in the reference genome annotation section; low-expressed genes were filtered further if the mean EU RNA-seq read count of control and A-485 treatment condition was less than 20. 東島佳毅
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694653942572869?thread_ts=1694596296.008679&cid=CFXHZD9TR)
It looks like GRO-seq or PRO-seq but I don’t think same. I will also make a GitHUB issue for this.
東島佳毅
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694656113463829?thread_ts=1694596296.008679&cid=CFXHZD9TR)
I have made the comments on a GitHUB as well. Thank you very much!
Edmund
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1694694535150549?thread_ts=1694596296.008679&cid=CFXHZD9TR)
Awesome thank you so much!
東島佳毅
  [6 months ago](https://nfcore.slack.com/archives/CFXHZD9TR/p1695205929007369?thread_ts=1694596296.008679&cid=CFXHZD9TR)
Hi again, I am tentatively setting the assay_type as “GROseq” and analyzing my EU-seq data. Then, I have the following error just after starting the pipeline. Do you have any idea how to solve this issue? Sorry to ask such a basic question. Thank you for your help in advance! file:///Users/higashijimayoshiki/Library/CloudStorage/Dropbox/Bioinformatics/230920_EU-seq_analysis/execution_report_2023-09-20_18-20-09.html
